### ISSUE TITLE
another run.bat issue

### ISSUE THREAD

**Issue by philchaub** [toyxyz/ComfyUI_toyxyz_test_nodes#26]
(setup.bat) seem to not work correctly, i suppose that could be about the version of python i have.
prehaps it's a python version problem.
i try to install all requirement manually and start cam.py and i have this message :
Traceback (most recent call last):
  File "cam.py", line 25, in <module>
    from pygrabber.dshow_graph import FilterGraph #Get camera list
  File "C:\Users\isisc\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\CaptureCam\venv\lib\site-packages\pygrabber\dshow_graph.py", line 51, in <module>
    Mat = np.ndarray[int, np.dtype[np.generic]]
TypeError: Type subscription requires python >= 3.9

so, what python version i need to install ?

**Comment by toyxyz** [comment]
Python version 3.10 is recommended. https://www.python.org/downloads/release/python-3106/
