### ISSUE TITLE
Webcam App dont capture

### ISSUE THREAD

**Issue by mp3pintyo** [toyxyz/ComfyUI_toyxyz_test_nodes#4]
Windows 11 error:
[ WARN:1@30.689] global window.cpp:302 cvGetWindowProperty No UI backends available. Use OPENCV_LOG_LEVEL=DEBUG for investigation
Exception in thread Thread-1 (capture_frames):
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "d:\AI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\CaptureCam\cam.py", line 318, in capture_frames
    if cv2.waitKey(1) & 0xFF == ord('q'):
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1338: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'

**Comment by toyxyz** [comment]
I have updated it. Try deleting the custom node folder and re-downloading it to see if you get the error.
