### ISSUE TITLE
更新后 无法使用

### ISSUE THREAD

**Issue by 1473725334** [toyxyz/ComfyUI_toyxyz_test_nodes#49]
11.2日作者更新，之后无法使用，啥问题

**Comment by toyxyz** [comment]
What exactly is the issue you're experiencing? Please elaborate a bit more, i'm currently adding some features. Try deleting the custom node completely and reinstalling it.

**Comment by 1473725334** [comment]
在11.2日我打开之后，安装的此节点便不可使用，截至发送此条评论之前，依旧无法使用，显示为红色节点，已使用多种方法重复安装，不知道是节点更新的问题，还是管理器的问题。还是需要重新补充什么？在此之前时可以使用 的。

**Comment by toyxyz** [comment]
> 在11.2日我打开之后，安装的此节点便不可使用，截至发送此条评论之前，依旧无法使用，显示为红色节点，已使用多种方法重复安装，不知道是节点更新的问题，还是管理器的问题。还是需要重新补充什么？在此之前时可以使用 的。

I have not been able to reproduce the issue, please show me the error message you see in the cmd.

**Comment by 1473725334** [comment]
cmd显示导入失败，

**Comment by toyxyz** [comment]
> cmd显示导入失败，

Is there any text that says '~module not found'?

**Comment by 1473725334** [comment]
问题以得到解决，我更新了toruch和yhtho，但我不知道这是不是行之有效的方法。

**Comment by toyxyz** [comment]
> 问题以得到解决，我更新了toruch和yhtho，但我不知道这是不是行之有效的方法。

A version difference in torch could also be the cause. Good for you if the issue is resolved.

**Comment by lzhfdwu007** [comment]
Similar problem, import failed after update
Error message is as follows

Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\__init__.py", line 12, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\toyxyz_test_nodes.py", line 13, in <module>
    from cv2.ximgproc import guidedFilter
ImportError: cannot import name 'guidedFilter' from 'cv2.ximgproc' (unknown location)

Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes module for custom nodes: cannot import name 'guidedFilter' from 'cv2.ximgproc' (unknown location)

**Comment by toyxyz** [comment]
> Similar problem, import failed after update Error message is as follows
> 
> Traceback (most recent call last): File "D:\ComfyUI\ComfyUI\nodes.py", line 2012, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes__init__.py", line 12, in imported_module = importlib.import_module(".{}".format(module_name), **name**) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "importlib__init__.py", line 126, in import_module File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\toyxyz_test_nodes.py", line 13, in from cv2.ximgproc import guidedFilter ImportError: cannot import name 'guidedFilter' from 'cv2.ximgproc' (unknown location)
> 
> Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes module for custom nodes: cannot import name 'guidedFilter' from 'cv2.ximgproc' (unknown location)

If you are using the portable version, go to the path where 'Python_embeded' is located on the cmd and then run:

python_embeded/python.exe -s -m pip install opencv-contrib-python

**Comment by wangdanx** [comment]
I also have this problem now. Whether updating torch or python, the import fails.

**Comment by toyxyz** [comment]
> I also have this problem now. Whether updating torch or python, the import fails.

Have you tried this ?  python_embeded/python.exe -s -m pip install opencv-contrib-python

**Comment by 1473725334** [comment]
> > I also have this problem now. Whether updating torch or python, the import fails.
> 
> Have you tried this ? python_embeded/python.exe -s -m pip install opencv-contrib-python

本来之前通过更新 opencv-contrib-python，是可以解决的，但是就在使用两天后，我不知道是使用了什么？导致再也无法导入，各种方法都试过了，理论上来说是依赖冲突，也是通过更新依赖得到的结果，但我没有有效的解决方法，

**Comment by toyxyz** [comment]
> > > I also have this problem now. Whether updating torch or python, the import fails.
> > 
> > 
> > Have you tried this ? python_embeded/python.exe -s -m pip install opencv-contrib-python
> 
> 本来之前通过更新 opencv-contrib-python，是可以解决的，但是就在使用两天后，我不知道是使用了什么？导致再也无法导入，各种方法都试过了，理论上来说是依赖冲突，也是通过更新依赖得到的结果，但我没有有效的解决方法，

Can you show me the error message?

**Comment by 1473725334** [comment]
> > > > I also have this problem now. Whether updating torch or python, the import fails.
> > > 
> > > 
> > > Have you tried this ? python_embeded/python.exe -s -m pip install opencv-contrib-python
> > 
> > 
> > 本来之前通过更新 opencv-contrib-python，是可以解决的，但是就在使用两天后，我不知道是使用了什么？导致再也无法导入，各种方法都试过了，理论上来说是依赖冲突，也是通过更新依赖得到的结果，但我没有有效的解决方法，
> 
> Can you show me the error message?
我没准备纠结了，因为我已经纠结了好几天了，今天找到秋叶大神的安装包，依然不行，我找了一个另外的整合包，正在下载，但愿他能处理好，其他等结果出来再说。但我翻译的一句话就是，解析依赖包出错。
