### ISSUE TITLE
import failed after update

### ISSUE THREAD

**Issue by lzhfdwu007** [toyxyz/ComfyUI_toyxyz_test_nodes#51]
Error message is as follows

Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\__init__.py", line 12, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\toyxyz_test_nodes.py", line 13, in <module>
    from cv2.ximgproc import guidedFilter
ImportError: cannot import name 'guidedFilter' from 'cv2.ximgproc' (unknown location)

Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes module for custom nodes: cannot import name 'guidedFilter' from 'cv2.ximgproc' (unknown location)

**Comment by toyxyz** [comment]
Seems like OpenCV problem. If you are using the portable version, go to the path where 'Python_embeded' is located on the cmd and then run:

`python_embeded/python.exe -s -m pip install opencv-contrib-python`

**Comment by T3chRomanc3r** [comment]
```
PS D:\ComfyUI_windows_portable> python_embeded/python.exe -s -m pip install opencv-contrib-python
Requirement already satisfied: opencv-contrib-python in d:\comfyui_windows_portable\python_embeded\lib\site-packages (4.11.0.86)
Requirement already satisfied: numpy>=1.21.2 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-contrib-python) (1.26.4)
```

  0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes

**Comment by toyxyz** [comment]
> ```
> PS D:\ComfyUI_windows_portable> python_embeded/python.exe -s -m pip install opencv-contrib-python
> Requirement already satisfied: opencv-contrib-python in d:\comfyui_windows_portable\python_embeded\lib\site-packages (4.11.0.86)
> Requirement already satisfied: numpy>=1.21.2 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-contrib-python) (1.26.4)
> ```
> 
> 0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes

Try uninstalling the existing one first, then reinstalling it. 

```
pip uninstall opencv-python
pip uninstall opencv-contrib-python

pip install opencv-python
pip install opencv-contrib-python
```
