### ISSUE TITLE
This node cannot be loaded，use"pip install opencv-contrib-python" can not fix that

### ISSUE THREAD

**Issue by foreverwx129** [toyxyz/ComfyUI_toyxyz_test_nodes#53]
Traceback (most recent call last):
  File "F:\envs\ComfyUI\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\__init__.py", line 12, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\ComfyUI\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\toyxyz_test_nodes.py", line 13, in <module>
    from cv2.ximgproc import guidedFilter
ImportError: cannot import name 'guidedFilter' from 'cv2.ximgproc' (unknown location)

Cannot import F:\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes module for custom nodes: cannot import name 'guidedFilter' from 'cv2.ximgproc' (unknown location)

**Comment by toyxyz** [comment]
Try uninstalling and reinstalling existing installations of opencv. 

```
pip uninstall opencv-python
pip uninstall opencv-contrib-python

pip install opencv-python
pip install opencv-contrib-python
```

**Comment by foreverwx129** [comment]
Thank you very much, I fix it now.
