### ISSUE TITLE
Unable to load custom nodes after installation 

### ISSUE THREAD

**Issue by sbp2156** [toyxyz/ComfyUI_toyxyz_test_nodes#54]
The installation appears to be successful, but the following output occurs in the scripts when restarting ComfyUI, and the nodes still appear in red. I was using this earlier without issues, but I had to reinstall it due to some problems.

Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\ComfyUI_windows_portable\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\toyxyz_tools\\__init__.py'

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\toyxyz_tools module for custom nodes: [Errno 2] No such file or directory: 'C:\\AI\\ComfyUI_windows_portable\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\toyxyz_tools\\__init__.py'

**Comment by toyxyz** [comment]
This looks like iniy.py was deleted for some reason. Try deleting the custom node completely and reinstalling it.

**Comment by sbp2156** [comment]
hey I tried everything but somehow the extension seems to not work - can you share a version without the update

**Comment by toyxyz** [comment]
Have you updated Comfyui to the latest version? 

You can use git checkout to use older versions of commits. 
https://stackoverflow.com/a/18037546/22334744

**Comment by toyxyz** [comment]
Try uninstalling and reinstalling existing installations of opencv.

If you're using the portable version, run the following from your comfyui location 

Like this : `python_embeded/python.exe -s -pip uninstall opencv-python`

```
pip uninstall opencv-python
pip uninstall opencv-contrib-python

pip install opencv-python
pip install opencv-contrib-python
```

**Comment by sbp2156** [comment]
hey I could not install the custome nodes in the workflow but I found a solution of using screen share by Mixlab- https://github.com/shadowcz007/comfyui-mixlab-nodes

but thanks for the support I would also suggest you to check it out 

<img width="1100" alt="Screenshot 2024-11-19 095323" src="https://github.com/user-attachments/assets/fb769b1b-d043-480b-99ea-b48dfec78349">
